name: Create EXE

on:
  push:
    branches:
      - main  # Adjust to your branch name

jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner with Node.js 16

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.0  # Specify the Python version you need
          architecture: x64  # Use x64 or x86 based on your requirements

      - name: Install Dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt
        working-directory: ./  # Modify this path

      - name: Build EXE
        run: |
          pyinstaller --noconfirm --onefile --windowed --name "FaceAttendanceSystem" --add-data "src;src/" --clean  --distpath ./output "main.py"
        working-directory: ./  # Modify this path

      - name: Copy EXE to GitHub workspace
        run: |
          git config --global user.email "chandanhans2003@gmail.com"
          git config --global user.name "ChandanHans"
          git add -f ./output/FaceAttendanceSystem.exe
          git commit -m "Update FaceAttendanceSystem.exe"
          git push
